- id: '1541621770207'
  alias: Update Dates
  trigger:
  - at: 00:01
    platform: time
  condition: []
  action:
  - data:
      entity_id: sensor.floorplan_date
    service: homeassistant.update_entity
  - data:
      entity_id: sensor.date_tomorrow
    service: homeassistant.update_entity
  - data:
      entity_id: sensor.date_two_days
    service: homeassistant.update_entity
- id: '1548894176255'
  alias: Notify Water Heater Leak
  trigger:
  - entity_id: binary_sensor.water_heater_liquid_detected
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      message: WATER HEATER IS LEAKING
    service: notify.ios_michaels_iphone
  - data:
      data:
        type: announce
      message: The Water Heater is Leaking!
    service: notify.alexa_media_everywhere
- id: '1551023960476'
  alias: Set Theme at Startup
  trigger:
  - event: start
    platform: homeassistant
  condition: []
  action:
  - data:
      name: slate
    service: frontend.set_theme
- id: '1551026675204'
  alias: Start Homekit
  trigger:
  - event: start
    platform: homeassistant
  condition: []
  action:
  - delay: 00:02
  - service: homekit.start
- id: '1551640131279'
  alias: Bedroom Lights On
  trigger:
  - entity_id: sensor.hue_switch
    platform: state
    to: 1_click_up
  condition: []
  action:
  - data:
      entity_id:
      - light.bedroom_ceiling
      - light.bedroom
    service: light.turn_on
- id: '1551640136749'
  alias: Bedroom Lights Off
  trigger:
  - entity_id: sensor.hue_switch
    platform: state
    to: 4_click_up
  condition: []
  action:
  - data:
      entity_id:
      - light.bedroom_ceiling
      - light.bedroom
    service: light.turn_off
- id: '1546740131279'
  alias: Main Floor From Bedroom On
  trigger:
  - entity_id: sensor.hue_switch
    platform: state
    to: 2_click_up
  condition: []
  action:
  - data:
      entity_id: switch.main_floor
    service: switch.turn_on
