- id: '1541621770207'
  alias: Update Dates
  trigger:
  - at: 00:01
    platform: time
  condition: []
  action:
  - data:
      entity_id: sensor.floorplan_date
    service: homeassistant.update_entity
  - data:
      entity_id: sensor.date_tomorrow
    service: homeassistant.update_entity
  - data:
      entity_id: sensor.date_two_days
    service: homeassistant.update_entity
- id: '1548894176255'
  alias: Notify Water Heater Leak
  trigger:
  - entity_id: binary_sensor.water_heater_liquid_detected
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      message: WATER HEATER IS LEAKING
    service: notify.ios_michaels_iphone
  - data:
      entity_id: media_player.office, media_player.office
      message: The Water Heater is Leaking!
    service: media_player.alexa_tts
  - data:
      entity_id: media_player.office, media_player.bedroom
      message: The Water Heater is Leaking!
    service: media_player.alexa_tts
  - data:
      entity_id: media_player.office, media_player.kitchen
      message: The Water Heater is Leaking!
    service: media_player.alexa_tts
- id: '1551023960476'
  alias: Set Theme at Startup
  trigger:
  - event: start
    platform: homeassistant
  condition: []
  action:
  - data:
      name: slate
    service: frontend.set_theme
- id: '1551026675204'
  alias: Start Homekit
  trigger:
  - event: start
    platform: homeassistant
  condition: []
  action:
  - delay: 00:02
  - service: homekit.start
