homeassistant:
  name: Home
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  elevation: 110
  unit_system: imperial
  time_zone: America/New_York
  customize: !include customize.yaml
  
http:
  base_url: !secret url
  api_password: !secret api_password
  ssl_certificate: /config/encrypt/fullchain.pem
  ssl_key: /config/encrypt/privkey.pem
  
############################################
##Zones##
############################################
zone:
  name: Work
  latitude: !secret latitude_work
  longitude: !secret longitude_work
  radius: 250
  icon: mdi:worker

zone 2:
  name: Parents
  latitude: !secret latitude_parents
  longitude: !secret longitude_parents
  radius: 200
  icon: mdi:home

############################################
##Initialize##
############################################
discovery:
updater:
frontend:
conversation:
history:
logbook:
logger:
sun:
recorder:
  purge_days: 14

############################################
##Include##
############################################
automation: !include_dir_list automation/
sensor: !include devices/sensors.yaml
switch: !include devices/switch.yaml
media_player: !include devices/media_players.yaml
group: !include groups.yaml
scene: !include_dir_list scene/
light:
  platform: lifx
  broadcast: 192.168.1.159
remote:
  platform: harmony
  name: Living Room
  host: 192.168.1.158
  activity: Watch TV
############################################
## Services ##
############################################
wink:
  email: !secret wink_email
  password: !secret wink_password
  client_id: !secret wink_client_id
  client_secret: !secret wink_client_secret
ecobee:
  api_key: !secret ecobee_key
  hold_temp: True
ifttt:
  key: !secret ifttt_key
notify:
  platform: pushover
  api_key: !secret pushover_api
  user_key: !secret pushover_user
device_tracker:
  - platform: icloud
    username: !secret icloud_user
    password: !secret icloud_pw 
  - platform: owntracks
    max_gps_accuracy: 200
emulated_hue:
  expose_by_default: false
mqtt:
  broker: !secret mqtt_broker
  port: 12681
  client_id: home-assistant-1
  username: !secret mqtt_user
  password: !secret mqtt_password

  
############################################
## Input Select ##
############################################
input_select:
  living_room_tv:
    name: Living Room TV
    options:
      - Powered Off
      - Watch TV
      - Plex Media Player
      - Netflix
      - Xbox One
      - Xbox 360
    initial: Powered Off
    icon: mdi:monitor
############################################
## Scripts ##
############################################
script:
  input_select_harmony:
    alias: "Start activity from input select"
    sequence:
      - service: remote.turn_on
        data_template:
          entity_id: remote.living_room
          activity: >
            {% if is_state("input_select.living_room_tv", "PowerOff") %}
                -1
            {% elif is_state("input_select.living_room_tv", "Watch TV") %}
                21316292
            {% elif is_state("input_select.living_room_tv", "Plex Media Player") %}
                22568347          
            {% elif is_state("input_select.living_room_tv", "Netflix") %}
                22568399
            {% elif is_state("input_select.living_room_tv", "Xbox One") %}
                21325006
            {% elif is_state("input_select.living_room_tv", "Xbox 360") %}
                22567878               
            {% endif %}
  bedtime_lamp:
    alias: " Bed time lamp"
    sequence:
      - alias: Lamp turn on
        service: light.turn_on
        data:
          entity_id: light.lamp
          brightness: 125
          color_temp: 200
      - delay:
           seconds: 30
      - alias: Lamp turn off
        service: light.turn_off
        data:
          entity_id: light.lamp
  main_level_on:
    alias: "Turn on main floor"
    sequence:
      - service: light.turn_on
        data:
          entity_id: light.lamp
          brightness: 255
          color_temp: 200
      - service: light.turn_on
        data:
          entity_id: light.kitchen
          brightness: 200
      - service: light.turn_on
        data:
          entity_id: light.cabinet
          brightness: 255
          color_temp: 240
      - service: remote.turn_on
        data_template:
          entity_id: remote.living_room
          activity: 21316292
  main_level_off:
    alias: "Turn off main floor"
    sequence:
      - service: light.turn_off
        data:
          entity_id: light.lamp
      - service: light.turn_off
        data:
          entity_id: light.kitchen
      - service: light.turn_off
        data:
          entity_id: light.cabinet
      - service: remote.turn_off
        data_template:
          entity_id: remote.living_room