homeassistant:
  name: Home
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  elevation: 110
  unit_system: imperial
  time_zone: America/New_York
  customize: !include customize.yaml
  packages: !include_dir_named packages
http:
  base_url: !secret url
  api_password: !secret api_password
  ssl_certificate: /config/encrypt/fullchain.pem
  ssl_key: /config/encrypt/privkey.pem
  ip_ban_enabled: True
  login_attempts_threshold: 5
############################################
##Zones##
############################################
zone:
  name: Work
  latitude: !secret latitude_work
  longitude: !secret longitude_work
  radius: 300
  icon: mdi:worker
zone 2:
  name: Parents
  latitude: !secret latitude_parents
  longitude: !secret longitude_parents
  radius: 300
  icon: mdi:home
zone 3:
  name: Home
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  radius: 200
  icon: mdi:home
############################################
##Initialize##
############################################
discovery:
ios:
  push:
    categories:
      - name: door
        identifier: 'lock'
        actions:
          - identifier: 'UNLOCK_DOOR'
            title: 'Yes'
            activationMode: 'background'
            authenticationRequired: no
            destructive: yes
            behavior: 'default'
          - identifier: 'DISMISS'
            title: 'Dismiss'
            activationMode: 'background'
            authenticationRequired: no
            destructive: no
            behavior: 'default'
config:
updater:
frontend:
conversation:
map:
device_tracker:
  - platform: owntracks_http
history:
  exclude:
    domains:
      - automation
    entities:
      - sensor.time
logbook:
  exclude:
    entities:
      - sensor.time
#logger:
sun:
recorder:
  purge_interval: 4
  purge_keep_days: 8
  exclude:
    domains:
      - media_player
############################################
##Include##
############################################
automation: !include_dir_list automation/
sensor: !include_dir_list sensors/
binary_sensor: !include_dir_list binary_sensors/
input_boolean: !include_dir_merge_named input_boolean/
input_select: !include_dir_merge_named input_select/
switch: !include_dir_list switches/
group: !include groups.yaml
scene: !include_dir_list scene/
script: !include_dir_merge_named script/

media_player:
  - platform: plex
light:
  - platform: lifx
  - platform: hue
    host: 192.168.1.193
remote:
  platform: harmony
  name: Living Room
  host: 192.168.1.158
  activity: Watch TV
ecobee:
  api_key: !secret ecobee_key
  hold_temp: True

panel_custom: 
  - name: floorplan
    sidebar_title: Floorplan
    sidebar_icon: mdi:home
    url_path: floorplan
    config: !include floorplan.yaml
############################################
## Services ##
############################################
wink:
  email: !secret wink_email
  password: !secret wink_password
  client_id: !secret wink_client_id
  client_secret: !secret wink_client_secret
ifttt:
  key: !secret ifttt_key
notify:
  platform: pushover
  api_key: !secret pushover_api
  user_key: !secret pushover_user
emulated_hue:
  expose_by_default: false
mqtt:
  broker: !secret mqtt_broker
  port: !secret mqtt_port
  client_id: home-assistant-1
  username: !secret mqtt_user
  password: !secret mqtt_password
tts:
  - platform: google