homeassistant:
  name: Home
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  elevation: 110
  unit_system: imperial
  time_zone: America/New_York
  customize: !include customize.yaml
  
http:
  base_url: !secret url
  api_password: !secret api_password
  ssl_certificate: /config/encrypt/fullchain.pem
  ssl_key: /config/encrypt/privkey.pem
  ip_ban_enabled: True
  login_attempts_threshold: 5

############################################
##Zones##
############################################
zone:
  name: Work
  latitude: !secret latitude_work
  longitude: !secret longitude_work
  radius: 300
  icon: mdi:worker

zone 2:
  name: Parents
  latitude: !secret latitude_parents
  longitude: !secret longitude_parents
  radius: 300
  icon: mdi:home

zone 3:
  name: Home
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  radius: 200
  icon: mdi:home

############################################
##Initialize##
############################################
#discovery:
ios:
updater:
frontend:
conversation:
history:
  exclude:
    domains:
      - automation
logbook:
#logger:
sun:
recorder:
  purge_days: 10
tts:
  - platform: google

############################################
##Include##
############################################
automation: !include_dir_list automation/
sensor: !include devices/sensors.yaml
binary_sensor: !include devices/binary_sensors.yaml
switch: !include devices/switch.yaml
media_player: !include devices/media_players.yaml
group: !include groups.yaml
scene: !include_dir_list scene/
script: !include_dir_merge_named script/

light:
  platform: lifx
remote:
  platform: harmony
  name: Living Room
  host: 192.168.1.158
  activity: Watch TV
ecobee:
  api_key: !secret ecobee_key
  hold_temp: True

  ############################################
## Services ##
############################################
wink:
  email: !secret wink_email
  password: !secret wink_password
  client_id: !secret wink_client_id
  client_secret: !secret wink_client_secret

ifttt:
  key: !secret ifttt_key
notify:
  platform: pushover
  api_key: !secret pushover_api
  user_key: !secret pushover_user
  
emulated_hue:
  expose_by_default: false
#mqtt:
#  broker: !secret mqtt_broker
#  port: 12681
#  client_id: home-assistant-1
#  username: !secret mqtt_user
#  password: !secret mqtt_password

  
############################################
## Input Select ##
############################################
input_select:
  living_room_tv:
    name: Living Room TV
    options:
      - Powered Off
      - Watch TV
      - Plex Media Player
      - Netflix
      - Xbox One
      - Xbox 360
    initial: Powered Off
    icon: mdi:monitor
