homeassistant:
  name: Home
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  elevation: 110
  unit_system: imperial
  time_zone: America/New_York
  customize: !include customize.yaml
  packages: !include_dir_named packages
http:
  base_url: !secret url
  use_x_forwarded_for: true
  trusted_proxies: 172.17.0.7
############################################
##Zones##
#Test#
############################################
zone:
  name: Work
  latitude: !secret latitude_work
  longitude: !secret longitude_work
  radius: 300
  icon: mdi:worker
zone 2:
  name: Parents
  latitude: !secret latitude_parents
  longitude: !secret longitude_parents
  radius: 300
  icon: mdi:home
zone 3:
  name: Home
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  radius: 200
  icon: mdi:home
############################################
##Initialize##
############################################
discovery:
  ignore:
    - igd
zwave:
  usb_path: /dev/ttyUSB0
  network_key: !secret network_key_z_wave
  device_config:
    light.kitchen:
      refresh_value: true
      delay: 3
      polling_intensity: 1
zha:
  usb_path: /dev/ttyUSB1
  database_path: /config/zigbee.db
ios:
  push:
    categories:
      - name: schedule
        identifier: 'sched'
        actions:
          - identifier: 'HOME'
            title: 'Home'
            activationMode: 'background'
            authenticationRequired: no
            destructive: no
            behavior: 'default'
          - identifier: 'OFFICE'
            title: 'Office'
            activationMode: 'background'
            authenticationRequired: no
            destructive: no
            behavior: 'default'
          - identifier: 'WEEKEND'
            title: 'Weekend'
            activationMode: 'background'
            authenticationRequired: no
            destructive: no
            behavior: 'default'
config:
updater:
python_script:
conversation:
system_health:
custom_updater:
  card_urls:
    - https://raw.githubusercontent.com/kalkih/mini-media-player/master/tracker.json
    - https://raw.githubusercontent.com/kalkih/mini-graph-card/master/tracker.json
    - https://raw.githubusercontent.com/keatontaylor/alexa_media_player/master/custom_components.json
frontend:
  javascript_version: latest
  themes: !include_dir_merge_named themes
map:

history:
  exclude:
    domains:
      - automation
      - group
    entities:
      - sensor.time
logbook:
  exclude:
    entities:
      - sensor.time
#logger:
sun:
recorder:
  purge_interval: 4
  purge_keep_days: 8
  exclude:
    domains:
      - media_player
influxdb:
  host: 192.168.1.250
  default_measurement: state
  exclude:
    domains:
      - automation
      - script
      - group
############################################
##Alexa##
############################################
alexa:
  smart_home:
    filter:
      include_domains:
        - light
        - fan
    entity_config:
      fan.living_room_fan:
        display_categories: SWITCH
      fan.bedroom_fan:
        display_categories: SWITCH


############################################
##Include##
############################################
automation old: !include_dir_list automation/
automation: !include automations.yaml
sensor: !include_dir_list sensors/
binary_sensor: !include_dir_list binary_sensors/
input_boolean: !include_dir_merge_named input_boolean/
input_select: !include_dir_merge_named input_select/
switch: !include_dir_list switches/
#group: !include groups.yaml
script: !include_dir_merge_named script/

shell_command:
  office_roku_on: "curl -X POST http://192.168.1.180:8060/keypress/home"
  office_plex: "curl -X POST http://192.168.1.180:8060/launch/13535"
  office_youtube: "curl -X POST http://192.168.1.180:8060/launch/837"
  office_tv: "curl -X POST http://192.168.1.180:8060/launch/195316"
  office_netflix: "curl -X POST http://192.168.1.180:8060/launch/12"
  office_cnbc: "curl -X POST http://192.168.1.180:8060/launch/195316?contentId=cuR5rpHUIxk&mediaType=movie"
  office_espn: "curl -X POST http://192.168.1.180:8060/launch/195316?contentId=cqH1uQ4ilPI&mediaType=movie"
  bedroom_roku_on: "curl -X POST http://192.168.1.219:8060/keypress/PowerOn"
  bedroom_roku_off: "curl -X POST http://192.168.1.219:8060/keypress/PowerOff"
  bedroom_plex: "curl -X POST http://192.168.1.219:8060/launch/13535"
  bedroom_youtube: "curl -X POST http://192.168.1.219:8060/launch/837"
  bedroom_tv: "curl -X POST http://192.168.1.219:8060/launch/195316"
  bedroom_netflix: "curl -X POST http://192.168.1.219:8060/launch/12"
  bedroom_cnbc: "curl -X POST http://192.168.1.168:8060/launch/195316?contentId=cuR5rpHUIxk&mediaType=movie"
  bedroom_espn: "curl -X POST http://192.168.1.168:8060/launch/195316?contentId=cqH1uQ4ilPI&mediaType=movie"
    
shopping_list:

speedtestdotnet:

alexa_media:
  accounts:
    - email: !secret amazon_email
      password: !secret amazon_pass
      url: amazon.com
      
vacuum:
  - platform: roomba
    host: 192.168.1.226
    username: !secret roomba_user
    password: !secret roomba_pass

media_player:
  - platform: plex
    entity_namespace: 'plex'
    scan_interval: 5
    use_episode_art: true
    remove_unavailable_clients: false
  - platform: spotify
    client_id: !secret spotify_id
    client_secret: !secret spotify_secret
    
#camera:
#  - platform: generic
#    name: Spotify Cover
#    still_image_url: >
#      {% if is_state("sensor.spotify_song", "Nothing Playing")%}
#        {{ states.sensor.spotify_base_url.state }}/local/spotify_logo.png
#      {% else %}
#        {{ states.sensor.spotify_base_url.state }}{{ states.media_player.spotify.attributes.entity_picture }}
#      {% endif %}
light:
  - platform: switch
    name: Bedroom Ceiling
    entity_id: switch.bedroom_ceiling_light
  - platform: switch
    name: Living Room Ceiling
    entity_id: switch.living_room_ceiling
hue:
  bridges:
    - host: 192.168.1.193
homekit:
  auto_start: false
  filter:
    include_domains:
      - light
      - lock
      - switch
      - input_boolean
      - script
      - fan
remote:
  platform: harmony
  name: Living Room
  host: 192.168.1.158
  activity: Watch TV
  delay_secs: 0.7
ecobee:
  api_key: !secret ecobee_key
  hold_temp: True
weather:
  - platform: darksky
    api_key: !secret darksky_api
    name: Dark Sky
    mode: daily
panel_custom: 
  - name: floorplan
    sidebar_title: Floorplan
    sidebar_icon: mdi:home
    url_path: floorplan
    config: !include floorplan.yaml
############################################
## Services ##
############################################
ifttt:
  key: !secret ifttt_key
notify:
  - platform: pushover
    api_key: !secret pushover_api
    user_key: !secret pushover_user
  - platform: alexa_media
    name: alexa_media
emulated_hue:
  expose_by_default: false
mqtt:
  broker: !secret mqtt_broker
  port: !secret mqtt_port
  client_id: home-assistant-1
  username: !secret mqtt_user
  password: !secret mqtt_password
tts:
  - platform: google