title: Home Assistant

resources:
  - url: /local/custom_ui/dark-sky-weather-card.js?v=6.8
    type: js

views:
  - icon: mdi:home
    title: Main
    badges:
      - updater.updater
    path: main
    cards:
      - type: horizontal-stack
        cards:
          - type: picture-entity
            entity: script.goodbye
            image: /local/goodbye2.jpg
            show_info: false
            tap_action:
              action: toggle
          - type: picture-entity
            entity: script.good_night
            image: /local/good_night2.jpg
            show_info: false
            tap_action:
              action: toggle
      - type: horizontal-stack
        cards:
          - type: light
            entity: light.living_room
          - type: entity-button
            entity: lock.front_door
            tap_action:
              action: toggle
      - type: entities
        title: Entry
        show_header_toggle: false
        entities:
          - lock.front_door
          - entity: binary_sensor.patio_door_opened
            name: Patio Door
          - input_boolean.ios_home
          - sensor.battery_front_door
          - light.porch
          - entity: device_tracker.michaels_iphone
            name: Michael
      - type: entities
        title: TV
        show_header_toggle: false
        entities:
          - remote.living_room
          - sensor.living_room
          - input_select.living_room_tv
      - type: entities
        title: Fan
        show_header_toggle: false
        entities:
          - fan.living_room_fan
          - sensor.fan_mode
      - type: entities
        title: Commute
        entities:
          - binary_sensor.alternate_route
          - sensor.home_to_work_time
          - sensor.commute_home_time
      - type: entities
        title: Lights
        show_header_toggle: true
        entities:
          - light.living_room
          - light.living_room_ceiling
          - light.foyer
          - light.kitchen
          - light.cabinet
      - type: entity-button
        entity: switch.fireplace
        tap_action:
          action: toggle
      - type: entity-button
        entity: vacuum.roomba
        tap_action:
          action: more-info
  - icon: mdi:hotel
    title: Bedroom
    path: bedroom
    cards:
      - type: entities
        entities:
          - input_select.alarm_schedule
          - input_boolean.morning_alexa
          - input_boolean.night_youtube
          - input_boolean.bathroom_door_alexa
          - input_text.text1
          - binary_sensor.bathroom_door_opened
      - type: entities
        title: Bedroom Switches
        show_header_toggle: true
        entities:
          - switch.bedroom_roku
          - switch.bedroom_plex
          - light.bedroom
          - light.bedroom_ceiling
          - fan.bedroom_fan
      - type: media-control
        entity: media_player.roku_yn00yp848585
      - type: media-control
        entity: media_player.bedroom
      - type: entity-filter
        entities:
          - media_player.plex_bedroom_2
        state_filter:
          - 'unavailable'
          - 'playing'
          - 'paused'
          - 'idle'
        card:
          type: media-control
          entity: media_player.plex_bedroom_2
  - icon: mdi:access-point-network
    title: Network
    path: network
    cards:
      - type: entity-button
        entity: switch.wake_on_lan
        tap_action:
          action: toggle
      - type: vertical-stack
        cards:
          - type: markdown
            content: >
              # SPEEDTEST
          - type: gauge
            name: Download
            entity: sensor.speedtest_download
            min: 0
            max: 120
            severity:
              red: 0
              amber: 70
              green: 95
          - type: gauge
            name: Upload
            entity: sensor.speedtest_upload
            min: 0
            max: 120
            severity:
              red: 0
              amber: 70
              green: 95
          - type: gauge
            name: Ping
            entity: sensor.speedtest_ping
            min: 0
            max: 50
            severity:
              green: 0
              amber: 10
              red: 20
          - type: markdown
            content: >
              ---
      - type: entities
        title: Plex Downloads
        show_header_toggle: false
        entities:
          - switch.deluge_switch
          - entity: sensor.sonarr_disk_space
            name: Disk Space
          - sensor.deluge_status
          - sensor.deluge_down_speed
          - sensor.deluge_up_speed
      - type: entities
        title: Pi-Hole
        entities:
          - sensor.pihole_ads_blocked_today
          - sensor.pihole_ads_percentage_blocked_today
      - type: glance
        title: Device Status
        column_width: calc(100% / 3)
        show_state: false
        entities:
          - entity: binary_sensor.hub
            name: Wink Hub
          - binary_sensor.living_room_fan
          - binary_sensor.bedroom_fan
      - type: glance
        title: Battery Status
        column_width: calc(100% / 4)
        entities:
          - entity: sensor.michaels_iphone_battery_level
            name: iPhone
          - entity: sensor.ipad_battery_level
            name: iPad
          - entity: sensor.battery_front_door
            name: Front Door
          - entity: sensor.kiosk_battery
            name: Tablet
  - icon: mdi:thermometer-lines
    title: Weather
    path: weather
    cards:
      - type: vertical-stack
        cards:
          - type: thermostat
            entity: climate.thermostat
          - type: entities
            title: Ecobee
            entities:
              - climate.thermostat
              - sensor.thermostat_mode
              - entity: binary_sensor.temp_balance
                name: Difference
              - entity: binary_sensor.thermostat_occupancy
                name: 1st Floor Occupancy
              - entity: binary_sensor.office_occupancy
                name: 2nd Floor Occupancy
              - entity: sensor.thermostat_humidity
                name: Humidity
              - sensor.24_hour_ac_running
          - type: glance
            title: Thermostat
            column_width: calc(100% / 4)
            entities:
              - entity: sensor.thermostat_temperature
                name: Downstairs
              - entity: sensor.patio_door_temperature
                name: Kitchen
              - entity: sensor.office_temperature
                name: Upstairs
              - entity: sensor.bathroom_door_temperature
                name: Bathroom
          - type: history-graph
            title: "Thermostat - Prior 4 Hours"
            hours_to_show: 4
            entities:
              - sensor.thermostat_mode
      - type: weather-forecast
        entity: weather.dark_sky
  - icon: mdi:plex
    title: Plex
    path: plex
    cards:
#      - type: picture
#        image: /local/ombi.png
#        tap_action:
#          action: navigate
#          navigation_path: https://shire.pw/request
      - type: markdown
        content: >
          [![Image](/local/plex-logo.png)](https://shire.pw/request)
      - type: gauge
        entity: sensor.tautulli_total
        min: 0
        max: 3
        severity:
          green: 0
          amber: 2
          red: 3
      - type: entities
        entities:
          - entity: sensor.plex_list
            name: Users Streaming
      - type: entities
        entities:
          - entity: sensor.tautulli_total_bandwidth
            name: Streaming Bandwith
      - type: entity-filter
        entities:
          - media_player.plex_media_room_3
        state_filter:
          - 'unavailable'
          - 'playing'
          - 'paused'
          - 'idle'
        card:
          type: media-control
          entity: media_player.plex_media_room_3
      - type: entity-filter
        entities:
          - media_player.plex_bedroom_2
        state_filter:
          - 'unavailable'
          - 'playing'
          - 'paused'
          - 'idle'
        card:
          type: media-control
          entity: media_player.plex_bedroom_2
      - type: entity-filter
        entities:
          - media_player.plex_roku
        state_filter:
          - 'playing'
        card:
          type: media-control
          entity: media_player.plex_roku
  - icon: mdi:music
    title: Music
    path: music
    cards:
      - type: media-control
        entity: media_player.spotify
      - type: media-control
        entity: media_player.everywhere
      - type: media-control
        entity: media_player.upstairs
      - type: media-control
        entity: media_player.kitchen
      - type: media-control
        entity: media_player.bedroom
      - type: media-control
        entity: media_player.office
      - type: media-control
        entity: media_player.bathroom
  - icon: mdi:home-automation
    title: Automations
    path: automation
    cards:
      - type: picture-entity
        image: /local/guest_mode.jpg
        entity: input_boolean.guest_mode
        tap_action:
          action: toggle
      - type: entities
        title: Lock
        show_header_toggle: false
        entities:
          - automation.lock_when_away
          - automation.unlock_when_home
          - automation.lock_at_12_am
          - automation.code_entry_home
      - type: entities
        title: Lights
        show_header_toggle: false
        entities:
          - automation.cabinet_light_with_main
          - automation.cabinet_light_off_with_main
          - automation.porch_on_sunset
          - automation.porch_off_11pm
      - type: entities
        title: Plex
        show_header_toggle: false
        entities:
          - automation.plex_movie_play
          - automation.plex_movie_pause
          - automation.plex_movie_stop
      - type: entities
        title: Morning
        show_header_toggle: false
        entities:
          - automation.morning_for_home
          - automation.morning_for_office
          - automation.morning_downstairs_for_office
          - automation.light_on_for_office_trip
          - automation.schedule_set_home
          - automation.schedule_set_office
          - automation.schedule_set_weekend
          - automation.schedule_weekend_auto
          - automation.send_work_route
      - type: entities
        title: TV
        show_header_toggle: false
        entities:
          - automation.remote_external_update_living_room
          - automation.remote_start_activity_from_input_select_living_room_tv
          - automation.youtube_on_office
          - automation.youtube_on_bedroom
          - automation.plex_on_bedroom
      - type: entities
        title: Other
        show_header_toggle: false
        entities:
          - automation.ac_fan_balance
          - automation.activate_guest_mode
          - automation.deactivate_guest_mode
          - automation.notify_that_a_device_is_offline
          - automation.notify_that_a_device_is_back_online
          - automation.alexa_in_bathroom_on
          - automation.alexa_in_bathroom_off
          - automation.update_dates
          - automation.update_floorplan_time
excluded_entities:
  - media_player.michaels_alexa_apps
  - media_player.michaels_fire
  - media_player.this_device
  - weather.thermostat
  - scene.lock_door
  - scene.unlock_door
  - switch.front_lock
  - switch.harmony_night_bye
  - switch.office_funhaus
  - switch.bedroom_funhaus
  - script.start_fios
  - script.start_netflix
  - script.start_plex
  - script.start_xbox
  - script.start_youtube
  - script.tv_off
  - script.input_select_harmony
  - script.bedtime_lamp
  - script.lock_when_gone
  - script.night_light_home
  - script.echo_volume_up
  - script.youtube_for_bedroom
  - script.main_level_on
  - script.main_level_off
  - script.all_lights_on
  - script.all_lights_off
  - script.spotify_next
  - script.spotify_play_pause
  - script.spotify_previous
  - script.good_morning
  - script.patio_closed
  - script.patio_closed_night
  - sensor.floorplan_date
  - sensor.floorplan_time
  - sensor.plex_movie_time
  - sensor.living_room
  - sensor.spotify_artist
  - sensor.spotify_song
  - sensor.spotify_base_url
  - sensor.plex_video_type
  - history_graph.ac_fan
  - light.entertainment_area_1
  - light.left_sofa_lamp
  - light.right_sofa_lamp
  - light.tv_lamp
  - binary_sensor.plex_in_use
  - binary_sensor.mike
  - binary_sensor.parents
  - sensor.date_tomorrow
  - sensor.date_two_days
  