alias: Youtube on Bedroom
trigger:
  platform: state
  entity_id: switch.bedroom_youtube
  to: 'on'
action:
  - delay:
      seconds: 2
  - service: switch.turn_off
    entity_id: switch.bedroom_youtube