alias: Spotify off tablet
trigger:
  - platform: state
    entity_id: media_player.spotify
    to: 'paused'
    for:
      minutes: 3
  - platform: state
    entity_id: media_player.spotify
    to: 'idle'
    for:
      minutes: 3
condition:
  - condition: state
    entity_id: input_boolean.ios_home
    state: 'on'
action:
  - service: switch.turn_off
    entity_id: switch.spotify_switch