alias: iOS entry home
trigger:
  platform: event
  event_type: ios.notification_action_fired
  event_data:
    actionName: UNLOCK_DOOR
action:
  - service: lock.unlock
    entity_id: lock.front_door
  - service: script.night_light_home