alias: AC Fan Balance
trigger:
  platform: time_pattern
  hours: '/2'
  minutes: 00
  seconds: 00
condition:
  condition: template
  value_template: "{{ not is_state('climate.thermostat', 'off') }}"
action:
  service: climate.ecobee_set_fan_min_on_time
  data_template:
    entity_id: climate.thermostat
    fan_min_on_time: >
      {%- if is_state("binary_sensor.temp_balance", "on") -%}
        55
      {%- else -%}
        0
      {%- endif %}