alias: 'activate guest mode'
trigger:
  platform: state
  entity_id: input_boolean.guest_mode
  to: 'on'
action:
  - service: automation.turn_off
    entity_id:
      - automation.lock_at_12_am
      - automation.morning_for_home
      - automation.morning_for_office
      - automation.light_on_for_office_trip
      - automation.plex_movie_pause
      - automation.plex_movie_play
      - automation.plex_movie_stop
      - automation.morning_downstairs_for_office
      - automation.lock_when_away
      - automation.unlock_when_home