alias: 'activate guest mode'
trigger:
  platform: state
  entity_id: input_boolean.guest_mode
  to: 'on'
action:
  - service : automation.turn_off
    entity_id: automation.lock_at_12_am
  - service : automation.turn_off
    entity_id: automation.morning_for_home
  - service : automation.turn_off
    entity_id: automation.morning_for_office
  - service : automation.turn_off
    entity_id: automation.light_on_for_office_trip