alias: 'deactivate guest mode'
trigger:
  platform: state
  entity_id: input_boolean.guest_mode
  to: 'off'
action:
  - service: automation.turn_on
    entity_id:
      - automation.lock_at_12_am
      - automation.morning_for_home
      - automation.morning_for_office
      - automation.light_on_for_office_trip
      - automation.plex_movie_pause
      - automation.plex_movie_play
      - automation.plex_movie_stop
      - automation.morning_downstairs_for_office
      - automation.lock_when_away
      - automation.unlock_when_home
  - service: input_select.select_option
    data:
      entity_id: input_select.alarm_schedule
      option: Home