alias: Lock At 12 AM
trigger:
  platform: time
  at: '00:00:01'
condition:
  condition: state
  entity_id: lock.front_door
  state: 'unlocked'
action:
  - service: lock.lock
    data:
      entity_id: lock.front_door