alias: Morning Downstairs for Office
trigger:
  platform: time
  at: '06:18:00'
condition:
  condition: state
  entity_id: input_select.alarm_schedule
  state: 'Office'
action:
  - service: script.turn_on
    entity_id: script.main_level_on
  - delay: '00:00:40'
  - service: remote.send_command
    data_template:
      entity_id: remote.living_room
      command:
        - 5
        - 0
        - 6
        - Select
      device: 36789856