alias: Light on for Office Trip
trigger:
  platform: time
  at: '06:30:00'
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: input_select.alarm_schedule
      state: 'Office'
    - condition: sun
      before: sunrise
      after_offset: "0:15:00"
action:
    - service: light.turn_on
      data:
        entity_id: light.porch
        brightness: 255
    - delay:
        minutes: 20
    - service: light.turn_off
      entity_id: light.porch