alias: Morning for Office
trigger:
  platform: time
  at: '05:54:00'
condition:
  condition: state
  entity_id: input_select.alarm_schedule
  state: 'Office'
action:
  service: script.turn_on
  entity_id: script.good_morning