alias: Morning Downstairs for Office
trigger:
  platform: time
  at: '06:29:00'
condition:
  condition: state
  entity_id: input_select.alarm_schedule
  state: 'Office'
action:
  - service: script.turn_on
    entity_id: script.main_level_on