alias: Night light
trigger:
  platform: state
  entity_id: binary_sensor.mike
  from: 'off'
  to: 'on'
condition:
  condition: or
  conditions:
    - condition: sun
      after: sunset
      after_offset: "-0:20:00"
    - condition: sun
      before: sunrise
      after_offset: "0:20:00"
action:
  service: light.turn_on
  data:
    entity_id: light.lamp
    brightness: 255
    transition: 7
    color_temp: 200