alias: Plex Movie Stop
trigger:
  - platform: state
    entity_id: media_player.plex_media_room
    from: 'playing'
    to: 'idle'
  - platform: state
    entity_id: media_player.plex_media_room
    from: 'paused'
    to: 'idle'
condition:
  condition: or
  conditions:
    - condition: sun
      after: sunset
      after_offset: "-0:20:00"
    - condition: sun
      before: sunrise
      after_offset: "0:20:00"
action:
  - service: light.turn_on
    entity_id: light.living_room
    data:
      brightness: 255
      color_temp: 200
  - service: light.turn_off
    entity_id:
      - light.cabinet