alias: Plex Movie Pause
trigger:
  platform: state
  entity_id: media_player.plex_media_room
  to: 'paused'
condition:
  condition: and
  conditions:
    - condition: template
      value_template: '{{ states.media_player.plex_media_room.attributes.media_content_type == "movie" }}'
    - condition: template
      value_template: '{{ states.sun.sun.attributes.elevation <= 4 }}'
action:
  - service: light.turn_on
    data:
      entity_id: light.living_room
      brightness: 125
      color_temp: 200