alias: Plex Movie Stop
trigger:
  - platform: state
    entity_id: media_player.plex_media_room
    from: 'playing'
    to: 'idle'
  - platform: state
    entity_id: media_player.plex_media_room
    from: 'paused'
    to: 'idle'
condition:
  condition: and
  conditions:
    - condition: template
      value_template: '{{ states.media_player.plex_media_room.attributes.media_content_type == "movie" }}'
    - condition: template
      value_template: '{{ states.sun.sun.attributes.elevation <= 4 }}'
action:
  - service: light.turn_on
    entity_id: light.living_room
    data:
      brightness: 255
      color_temp: 200
  - service: light.turn_off
    entity_id:
      - light.cabinet