alias: Plex Movie Play
trigger:
  platform: state
  entity_id: media_player.plex_media_room
  to: 'playing'
condition:
  condition: and
  conditions:
    - condition: template
      value_template: '{{ states.media_player.plex_media_room.attributes.media_content_type == "movie" }}'
    - condition: template
      value_template: '{{ states.sun.sun.attributes.elevation <= 4 }}'
action:
  - service: light.turn_on
    data:
      entity_id: light.cabinet
      brightness: 125
      color_temp: 240
  - service: light.turn_off
    entity_id:
      - light.foyer
      - light.kitchen
      - light.living_room
      - light.living_room_ceiling
