alias: Schedule Set Home
trigger:
  platform: event
  event_type: ios.notification_action_fired
  event_data:
    actionName: HOME
action:
  - service: input_select.select_option
    data:
      entity_id: input_select.alarm_schedule
      option: Home