alias: Send work Route
trigger:
  platform: state
  entity_id: input_boolean.ios_home
  to: 'off'
condition:
  condition: and
  conditions:
    - condition: time
      after: '06:00:00'
      before: '08:00:00'
    - condition: state
      entity_id: input_select.alarm_schedule
      state: 'Office'
action:
  service: notify.ios_michaels_iphone
  data:
    title: "Navigation"
    message: |
      The trip to work will take {{states.sensor.home_to_work_time.state}} minutes.
      {% if is_state('binary_sensor.alternate_route', 'on')%}{{"ALTERNATE ROUTE!"}}
      {% endif%}Click to navigate
    data:
      url: waze://?favorite=work
