alias: notify that a device is offline
trigger:
  - platform: state
    entity_id: binary_sensor.bedroom_fan
    to: 'unavailable'
  - platform: state
    entity_id: binary_sensor.living_room_fan
    to: 'unavailable'
action:
  service: notify.ios_michaels_iphone
  data_template:
    message: >
      {{ trigger.entity_id.split('.')[1] }} is offline.