alias: Unlock When Home
trigger:
  platform: state
  entity_id: device_tracker.michael_iphone
  to: 'home'
action:
  - service: notify.ios_michael_iphone
    data_template:
      message: 'Unlock Front Door?'
      data:
        push:
          category: 'lock'