alias: Update Wink
trigger:
  platform: time
  hours: '/2'
  minutes: 00
  seconds: 00
action:
  - service: switch.turn_on
    data:
      entity_id: switch.wink_update
  - delay: 00:00:10
  - service: switch.turn_off
    data:
      entity_id: switch.wink_update